version: 2

models:
  - name: dim_store
    description: "Dimension table for store."
    columns:
      - name: store_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: store_name
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: address
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: city
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: zip_code
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: county_number
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: county
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
  - name: dim_item
    description: "Dimension table for item."
    columns:
      - name: item_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: pack
        description: "The number of bottles in a pack"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1  # Replace with your actual MIN(pack) result
                max_value: 160 # Replace with your actual MAX(pack) result
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: int64
      - name: bottle_volume_ml
        description: "The volume of the bottle in milliliters"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0 # Replace with your actual MIN(bottle_volume_ml) result
                max_value: 378000 # Replace with your actual MAX(bottle_volume_ml) result
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: int64        
      - name: item_description
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: category
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: category_name
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: vendor_number
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
      - name: vendor_name
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: string
